### ISSUE TITLE
wrong ID case type

### ISSUE THREAD

**Issue by Galope-Jhean** [PUP-BSIT/exercise-14-vrzn_webdev#12]
please see the ff line and correct it based on this [guideline](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

https://github.com/PUP-BSIT/exercise-14-vrzn_webdev/blob/8d3c1fcb38d09387ac02531733fd704bd8259921/Odrunia_Mark_Ryan/Odrunia_Mark_Ryan.html#L206

Also, I noticed in your JS that u reference these selector variables more than once

https://github.com/PUP-BSIT/exercise-14-vrzn_webdev/blob/8d3c1fcb38d09387ac02531733fd704bd8259921/Odrunia_Mark_Ryan/scripts.js#L36-L38
https://github.com/PUP-BSIT/exercise-14-vrzn_webdev/blob/8d3c1fcb38d09387ac02531733fd704bd8259921/Odrunia_Mark_Ryan/scripts.js#L75-L77

It's better to declare them once globally and use them through each function to avoid repeating yourself.

One more thing, your JS code is indented, refer to these lines. 

https://github.com/PUP-BSIT/exercise-14-vrzn_webdev/blob/8d3c1fcb38d09387ac02531733fd704bd8259921/Odrunia_Mark_Ryan/scripts.js#L35-L107

**Comment by Odrunia-Mark-Ryan** [comment]
issues fixed kindly review my code again, I already submit a pull request
