### ISSUE TITLE
wrong ID case type

### ISSUE THREAD

**Issue by Galope-Jhean** [PUP-BSIT/exercise-14-vrzn_webdev#14]
apologies for the oversight, kindly adhere to the [guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5) in the ff lines

https://github.com/PUP-BSIT/exercise-14-vrzn_webdev/blob/040c88cba65778afabc60d5a709ddae8fccf8614/naoe_adrian/naoe_adrian.html#L384

**Comment by Naoe-Adrian** [comment]
Thank you mate, I remove it because I realize I'm not using that anymore because _I modify my code in js last night_ . 🤍
